"""Initial schema

Revision ID: a46c155b7e27
Revises: 
Create Date: 2025-08-08 06:02:52.743909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46c155b7e27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fallback_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fallback_policies_id'), 'fallback_policies', ['id'], unique=False)
    op.create_index(op.f('ix_fallback_policies_name'), 'fallback_policies', ['name'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('rate_limit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=200), nullable=False),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limit_identifier', 'rate_limit_logs', ['identifier', 'window_start'], unique=False)
    op.create_index('idx_rate_limit_window', 'rate_limit_logs', ['window_start'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_id'), 'rate_limit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_identifier'), 'rate_limit_logs', ['identifier'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('api_key', sa.String(length=200), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('model_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=200), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_model_name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alias_name', 'model_mappings', ['alias_name'], unique=False)
    op.create_index('idx_alias_order', 'model_mappings', ['alias_name', 'order_index'], unique=False)
    op.create_index(op.f('ix_model_mappings_alias_name'), 'model_mappings', ['alias_name'], unique=False)
    op.create_index(op.f('ix_model_mappings_id'), 'model_mappings', ['id'], unique=False)
    op.create_table('provider_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=100), nullable=False),
    sa.Column('key_value_encrypted', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('current_daily_usage', sa.Integer(), nullable=True),
    sa.Column('current_monthly_usage', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'key_id', name='uq_provider_key_id')
    )
    op.create_index('idx_provider_key_priority', 'provider_keys', ['provider_id', 'priority'], unique=False)
    op.create_index('idx_provider_key_status', 'provider_keys', ['provider_id', 'status'], unique=False)
    op.create_index(op.f('ix_provider_keys_id'), 'provider_keys', ['id'], unique=False)
    op.create_index(op.f('ix_provider_keys_key_id'), 'provider_keys', ['key_id'], unique=False)
    op.create_table('requests_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('model_alias', sa.String(length=200), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_model_name', sa.String(length=200), nullable=True),
    sa.Column('key_id', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('fallback_chain_json', sa.JSON(), nullable=True),
    sa.Column('fallback_count', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('s3_request_key', sa.String(length=500), nullable=True),
    sa.Column('s3_response_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_audit_created', 'requests_audit', ['created_at'], unique=False)
    op.create_index('idx_request_audit_model', 'requests_audit', ['model_alias', 'created_at'], unique=False)
    op.create_index('idx_request_audit_provider', 'requests_audit', ['provider_id', 'created_at'], unique=False)
    op.create_index('idx_request_audit_tenant', 'requests_audit', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_requests_audit_id'), 'requests_audit', ['id'], unique=False)
    op.create_index(op.f('ix_requests_audit_request_id'), 'requests_audit', ['request_id'], unique=True)
    op.create_index(op.f('ix_requests_audit_tenant_id'), 'requests_audit', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_audit_tenant_id'), table_name='requests_audit')
    op.drop_index(op.f('ix_requests_audit_request_id'), table_name='requests_audit')
    op.drop_index(op.f('ix_requests_audit_id'), table_name='requests_audit')
    op.drop_index('idx_request_audit_tenant', table_name='requests_audit')
    op.drop_index('idx_request_audit_provider', table_name='requests_audit')
    op.drop_index('idx_request_audit_model', table_name='requests_audit')
    op.drop_index('idx_request_audit_created', table_name='requests_audit')
    op.drop_table('requests_audit')
    op.drop_index(op.f('ix_provider_keys_key_id'), table_name='provider_keys')
    op.drop_index(op.f('ix_provider_keys_id'), table_name='provider_keys')
    op.drop_index('idx_provider_key_status', table_name='provider_keys')
    op.drop_index('idx_provider_key_priority', table_name='provider_keys')
    op.drop_table('provider_keys')
    op.drop_index(op.f('ix_model_mappings_id'), table_name='model_mappings')
    op.drop_index(op.f('ix_model_mappings_alias_name'), table_name='model_mappings')
    op.drop_index('idx_alias_order', table_name='model_mappings')
    op.drop_index('idx_alias_name', table_name='model_mappings')
    op.drop_table('model_mappings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_limit_logs_identifier'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_id'), table_name='rate_limit_logs')
    op.drop_index('idx_rate_limit_window', table_name='rate_limit_logs')
    op.drop_index('idx_rate_limit_identifier', table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_fallback_policies_name'), table_name='fallback_policies')
    op.drop_index(op.f('ix_fallback_policies_id'), table_name='fallback_policies')
    op.drop_table('fallback_policies')
    # ### end Alembic commands ###
